include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - always_use_package_imports
    - avoid_relative_lib_imports
    - avoid_type_to_string
    - require_trailing_commas
    - sized_box_for_whitespace
    - sort_child_properties_last
    - use_colored_box
    - use_decorated_box
    - use_function_type_syntax_for_parameters
    - use_named_constants
    - use_string_buffers
    - secure_pubspec_urls
    - prefer_double_quotes
