name: only_bible_app
description: The only bible app you will ever need
publish_to: 'none'
version: 1.0.5+10

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: any
  path_provider: ^2.0.15
  just_audio: ^0.9.34
  shared_preferences: ^2.2.0
  flutter_native_splash: ^2.3.1
  flutter_swipe_detector: ^2.0.0
  cupertino_icons: ^1.0.5
  settings_ui: ^2.0.2
  get_storage: ^2.1.1
  share_plus: ^7.1.0
  url_launcher: ^6.1.12
  package_info_plus: ^4.1.0
  flutter_azure_tts: ^0.1.6
  http: ^0.13.6
  atoms_state: 0.0.2
  webview_flutter: ^4.7.0
  app_review: ^2.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/bibles/
    - assets/fonts/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon.png"
  android_12:
    image: "assets/icon.png"
    color: "#FFFFFF"