name: only_bible_app
description: The only bible app you will ever need
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.0.15
  just_audio: ^0.9.34
  shared_preferences: ^2.2.0
  flutter_native_splash: ^2.3.1
  flutter_swipe_detector: ^2.0.0
  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.0
  provider: ^6.0.5
  firebase_crashlytics: ^3.3.4
  firebase_performance: ^0.9.2+4
  firebase_storage: ^11.2.5
  settings_ui: ^2.0.2
  get_storage: ^2.1.1
  share_plus: ^7.1.0
  file_selector: ^1.0.0 # need this to fix android build

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_azure_tts: ^0.1.6
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/bibles/
    - assets/fonts/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/test2.png"
  remove_alpha_ios: true
  web:
    generate: true
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon.png"
  android_12:
    image: "assets/icon.png"
    color: "#FFFFFF"