// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa9-kLU9yy9g8cRJG7jh5kOA8Z77uI_Pg',
    appId: '1:584350822569:web:b4c020f0a7e40f7cfdf9b8',
    messagingSenderId: '584350822569',
    projectId: 'only-bible-app',
    authDomain: 'only-bible-app.firebaseapp.com',
    storageBucket: 'only-bible-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0XlcB1JwkUbYX6CUnf9TkW4UtNxFq2ag',
    appId: '1:584350822569:android:f03003ffd2d3d9d6fdf9b8',
    messagingSenderId: '584350822569',
    projectId: 'only-bible-app',
    storageBucket: 'only-bible-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqRrBRa3fVmoZby_b4submR2hjQkImgZc',
    appId: '1:584350822569:ios:73b8443b3dd48f40fdf9b8',
    messagingSenderId: '584350822569',
    projectId: 'only-bible-app',
    storageBucket: 'only-bible-app.appspot.com',
    iosClientId: '584350822569-93bboqrirsb1q4mm697qm6ja58mnnakg.apps.googleusercontent.com',
    iosBundleId: 'sh.pyros.onlyBibleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqRrBRa3fVmoZby_b4submR2hjQkImgZc',
    appId: '1:584350822569:ios:5d85f3e76fa02286fdf9b8',
    messagingSenderId: '584350822569',
    projectId: 'only-bible-app',
    storageBucket: 'only-bible-app.appspot.com',
    iosClientId: '584350822569-s9t1p0bb1gqj8fothe4s5lstvu9k7244.apps.googleusercontent.com',
    iosBundleId: 'sh.pyros.onlyBibleApp.RunnerTests',
  );
}
