name: Build
'on':
  push:
    branches:
      - master
jobs:
  build:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
          cache: true
      - run: echo -e "TTS_SUBSCRIPTION_KEY=${{ secrets.TTS_SUBSCRIPTION_KEY }}\nRESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" > .env
      - run: flutter build appbundle --debug --dart-define-from-file=.env
      - run: flutter build ios --release --no-codesign --dart-define-from-file=.env