name: Build
'on':
  push:
    branches:
      - master
jobs:
  build:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
          cache: true
      - run: flutter --disable-telemetry
      - run: flutter build appbundle
      - run: flutter build ios --release --no-codesign
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos --dart-define=TTS_SUBSCRIPTION_KEY=${{ secrets.TTS_SUBSCRIPTION_KEY }} --dart-define=RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
      - run: flutter build web --dart-define=TTS_SUBSCRIPTION_KEY=${{ secrets.TTS_SUBSCRIPTION_KEY }} --dart-define=RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
      - run: cp build/web/index.html build/web/privacy-policy.html
      - uses: actions/upload-pages-artifact@v1
        with:
          path: build/web
      - uses: actions/deploy-pages@v2