name: Setup env
description: Setup env
runs:
  using: "composite"
  steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        file_name: .env
        envkey_TTS_SUBSCRIPTION_KEY: ${{ secrets.TTS_SUBSCRIPTION_KEY }}
        envkey_RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}